name: Publish XML updates

on:
  workflow_dispatch: # manually (via GitHub UI)
  schedule:
    - cron: "0 10 * * 5" # every Friday at 10:00

jobs:
  get-next:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build-data-file
      - uses: actions/upload-artifact@v2
        with:
          name: next
          path: data.json

  publish:
    runs-on: ubuntu-20.04
    needs: get-next
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PARZHBOT_PAT }}
      - uses: actions/download-artifact@v2
        with:
          name: next
      - name: Set Git user name and email
        run: |2
          git config --global user.name 'parzhbot'
          git config --global user.email '59538037+parzhbot@users.noreply.github.com'
      - run: npm ci
      - run: npm version --git-tag-version $(npm run --silent compose-version-number:ci)
        env:
          VERSIONING_IS_ALLOWED: "true"
      - name: Publish to registry
        run: |2
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > .npmrc
          npm publish --tag latest
      - run: git push --follow-tags
